steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-east1-docker.pkg.dev/$PROJECT_ID/webhook-repo/sheet-service:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-east1-docker.pkg.dev/$PROJECT_ID/webhook-repo/sheet-service:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sheet-service
      - --image=us-east1-docker.pkg.dev/$PROJECT_ID/webhook-repo/sheet-service:$COMMIT_SHA
      - --region=us-east1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --min-instances=0
      - --concurrency=50
      - --update-env-vars=RESOURCE_SHEET_ID=1NlbdL1UxeFD-0Vog6TU-vecOfUE4jvbWVIhsrIlTrqw

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - us-east1-docker.pkg.dev/$PROJECT_ID/webhook-repo/sheet-service:$COMMIT_SHA
